[general]
logging_level = 20 #logging.INFO
bootstrap_servers = ["localhost:9092"]
topics = ["client", "department", "employee", "sale"]

[publisher]
raw_path = "./raw_data"
batch_size = 10

[subscriber]
delta_path = "./delta_tables"

[redshift]
url = "jdbc:redshift://testworkgroup.767397751477.ap-southeast-2.redshift-serverless.amazonaws.com:5439/dev"
user = "admin"
password = "My_Secure_Password_1"

[schemas]
schemas = """
{
    "client": { \
        "type": "struct", \
        "fields": [ \
            {"type": "string", "optional": false, "field": "id"}, \
            {"type": "string", "optional": true, "field": "first_name"}, \
            {"type": "string", "optional": true, "field": "last_name"} \
        ], \
        "optional": false, \
        "name": "client" \
    }, \
    "department": { \
        "type": "struct", \
        "fields": [ \
            {"type": "string", "optional": false, "field": "id"}, \
            {"type": "string", "optional": true, "field": "department"} \
        ], \
        "optional": false, \
        "name": "department" \
    }, \
    "employee": { \
        "type": "struct", \
        "fields": [ \
            {"type": "string", "optional": false, "field": "id"}, \
            {"type": "string", "optional": true, "field": "first_name"}, \
            {"type": "string", "optional": true, "field": "last_name"}, \
            {"type": "string", "optional": false, "field": "department_id"} \
        ], \
        "optional": false, \
        "name": "employee" \
    }, \
    "sale": { \
        "type": "struct", \
        "fields": [ \
            {"type": "string", "optional": false, "field": "id"}, \
            {"type": "string", "optional": false, "field": "employee_id"}, \
            {"type": "string", "optional": false, "field": "client_id"}, \
            {"type": "string", "optional": false, "field": "date"}, \
            {"type": "string", "optional": true, "field": "region"}, \
            {"type": "string", "optional": true, "field": "sale"} \
        ], \
        "optional": false, \
        "name": "sale" \
    } \
}
"""